### ISSUE TITLE
Issue on Run Now

### ISSUE THREAD

**Issue by skeenp-dcceew** [skeenp/agol_backup#18]
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Python39\lib\tkinter\__init__.py", line 1885, in __call__
    return self.func(*args)
  File "C:\Users\skeenp01\Documents\GitHub\agol_backup\backup_cfg_mgr.py", line 739, in _runnow
    backup_mgr.run([cfg_path], logger=self._logger)
  File "C:\Users\skeenp01\Documents\GitHub\agol_backup\backup_mgr.py", line 47, in run
    os.mkdirs(backup_dir)
AttributeError: module 'os' has no attribute 'mkdirs'

**Comment by skeenp-dcceew** [comment]
Also log.setup("backup_mgr", app_dir=app_dir, active=args.nolog, level=log_level) needs level for verbose to work and also set level in setup function

**Comment by skeenp-dcceew** [comment]
logger.exception("  > Service Export Failed")
               {tab missing} return Response.ExportNotSupported
